name: autorun
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 15 * * 1'

jobs:
  autorun:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: download env
        run: wget https://raw.githubusercontent.com/star574/freenom/main/.env.example && cp .env.example .env
      - name: user
        run: echo -e "FREENOM_PASSWORD='${{secrets.PASSWORD}}'\nFREENOM_USERNAME='${{secrets.USERNAME}}'" >> .env  
      - name: docker run 
        run: docker run -i --name freenom  -v $(pwd):/conf -v $(pwd)/logs:/app/logs luolongfei/freenom
      - name: wait
        run: sleep 10s
      - name: log
        run: docker logs freenom
